### ISSUE TITLE
Infinite camera rotations

### ISSUE THREAD

**Issue by dbirman** [VirtualBrainLab/Urchin#10]

**Comment by jshaker6** [comment]
To add on to camera fixes - I think it would be better to have the camera and light source rotate together. It seems like currently the light source is fixed

**Comment by dbirman** [comment]
Todos:

- [ ] Add unlimited rotations
- [ ] Add option to lock light to camera or to keep the light separate
- [ ] Add controls to move the light to set the scene (and controls from python)

**Comment by dbirman** [comment]
v0.3 - Light now locked to camera, no controls yet for light

**Comment by dbirman** [comment]
Hotfix into v0.4.1

**Comment by dbirman** [comment]
e77004f4ce693c3fb01d43874d4696f5bece5003
