### ISSUE TITLE
[major] Refactor API to use linked objects in Python and in the renderer

### ISSUE THREAD

**Issue by dbirman** [VirtualBrainLab/Urchin#20]
It would be much better for users to be able to directly interact with objects in Python rather than having to create neurons by a string name and then modify these with dictionary calls. For example it would be great to be able to do:
```
neurons = urn.create_neurons(100)
neurons.set_positions(neuron_positions)
neurons.set_colors("#FF0000")
```

etc for other features, with the main functionality hidden in the background.

**Comment by dbirman** [comment]
Aiming for v1.0 release for this

**Comment by dbirman** [comment]
Maybe use a DOTS style architecture for this? Store objects as entity references into data components?

**Comment by dbirman** [comment]
neuron1 = urchin.neuron.create(1) // returns a single neuron object
neuron1.set_position(0,0,0)
neuron1.set_color("#ffffff")

neurons = urchin.neuron.create(2) // returns a list of neurons [neuron1, neuron2]
neurons.set_position(neurons, [(0,0,0), (0,0,0)])
neurons.set_color(neurons, ["#000000", "#ffffff"])
       The idea here would also be to do a better job sanitizing inputs. Users should be allowed to e.g. pass in "#FFFFFF" or "FFFFFF" or "white" or [255, 255, 255] or [1,1,1] and the API should interpret all of those as being white. Hopefully you can see that for students this would be a lot more intuitive than the current "pass dictionaries around" thing?

**Comment by dbirman** [comment]
Note that we're using the https://github.com/VirtualBrainLab/Urchin/tree/refactor-api branch for this

**Comment by jasmine-schoch** [comment]
Starting to create primitives class: cc687056bcd15561076c28adc185e548db3debf7

**Comment by jasmine-schoch** [comment]
When sanitizing inputs- also modify code to deal with singular brackets when sent a list of objects only containing one list

e.g. urchin.primitives.set_positions(cubes,[[2,2,2]]) should also work with urchin.primitives.set_positions(cubes,[2,2,2])

**Comment by jasmine-schoch** [comment]
Add boolean variable for whether object still exists in scene or not (set to false when deleting)

**Comment by jasmine-schoch** [comment]
[] line plural functions? esp for set position

**Comment by dbirman** [comment]
Small thing I noticed looking at these new files: be careful with parameter names in Python, we're using snack_case for everything except classes which are in CamelCase

**Comment by jasmine-schoch** [comment]
Camera function: create/delete functions implemented within API, but don't think it actually exists within Urchin?

**Comment by dbirman** [comment]
The camera features need to be implemented still. For now just make a function on the Unity side that sends back a LogWarning message saying something like "Multiple cameras are not yet implemented"

**Comment by jasmine-schoch** [comment]
refactored Camera API: c7dd3ff2d0e03edc6a5b45685f1a37254c3ccdcb

**Comment by jasmine-schoch** [comment]
okok so to work around it, I have the create function within python for the sake of creating/naming the python object, but does not do anything on the Unity end. People can just use it to reference other functions as "camera.set_position()" etc,  but all of the methods within aren't accessing any sort of camera id, since unity is currently built on the one default camera. This adds one extra step for when accessing camera commands on the notebook side, but it keeps for consistency with the rest of the classes/features. Later when we implement things on the unity end for multiple cameras, we will have to go back and update the api to use indexes when calling the camera functions.

867502c5b54a64c1f4cc15f64ec306a322ebd556

**Comment by jasmine-schoch** [comment]
set_probe_style is commented out-- is there a specific reason for that? I'll go ahead and add it in the new API and we can go back and comment it out later if necessary

**Comment by dbirman** [comment]
Not yet implemented in Unity, you can open another issue for it to keep track if there isn't one already

**Comment by jasmine-schoch** [comment]
probes: 9c2681f98480c00d52779eb01823f71726a61900

note: I changed the 'size' methods to 'scale' since that's what all of the other objects used for consistency
