### ISSUE TITLE
Add LineRenderer feature

### ISSUE THREAD

**Issue by dbirman** [VirtualBrainLab/Urchin#60]

**Comment by dbirman** [comment]
(for implementation when pair coding)

**Comment by jasmine-schoch** [comment]
Python API: add 3 functions
- [ ] CreateLine
- [ ] DeleteLine
- [ ] SetLinePosition
- [ ] SetLineColor

Server functionality: (server.js)
- [ ] echo function calls

Unity:
- [ ] handle function calls-- class: um_client
- [ ] write new line renderer manager class

**Comment by jasmine-schoch** [comment]
manager class added: a8ec285ca5669f2f84253d6d0f2270e48d3abba6

**Comment by jasmine-schoch** [comment]
Python API + Server functionality:
81c643df14a0c5892f5825c1d2f2c590b79893da

**Comment by jasmine-schoch** [comment]
d0031005fdcc0280382174b77872d68777f8359d
