### ISSUE TITLE
Primitive Mesh Manager

### ISSUE THREAD

**Issue by jasmine-schoch** [VirtualBrainLab/Urchin#62]

**Comment by dbirman** [comment]
Okay, so this manager will handle creating, positioning, scaling, and color of cubes and spheres (and eventually other kinds of meshes). This manager will work by keeping a Dictionary<string, GameObject> mapping the names of the objects to the gameobject in the scene.

Unity
- [ ] Add PrimitiveMeshManager
- [ ] Create a Prefab that is just a cube (by creating a cube in the scene, it's one of the options when you right click in the hierarchy)
- [ ] Add a CreateMesh function that instantiates the cube as default
- [ ] DeleteMesh
- [ ] Add SetPosition, SetScale, and SetColor functions
- [ ] Add the UM_Client code to handle receiving messages from the API

We'll add the ability to swap between cubes/spheres later once you have this basic functionality working.

Server
- [ ] Add the server echo calls

Python API
- [ ] Add the renderer calls 

Also add a new Examples/basics/primitives.ipynb script and populate it with tests for all the functions that you write.

When we meet Wednesday if you've gotten through some/most of that we can work on the more complicated stuff:
- [ ] The primitives need to have a reference coordinate that they are parented to, which should depend on the current CoordinateSpace that is loaded
- [ ] Add code to swap meshes between sphere/cube, or instantiate spheres in the first place
- [ ] Replace the existing neuron code with this new code
- [ ] Add SetMaterial functions

**Comment by jasmine-schoch** [comment]
Adding Manager + Prefab + CreateMesh function: 0cd7aba3122afe317b2a162825717aab7df6ae95

**Comment by jasmine-schoch** [comment]
Adding remaining functions: 7fc66c70c314eb694f1a9f6aa70840f52293c578

**Comment by jasmine-schoch** [comment]
Added server echo calls: 4bb55f6150699ef157ca559bee87edd63f0ab9e6

**Comment by jasmine-schoch** [comment]
Added renderer calls to API: cd268c769345825c488902cd3258f24d0e79f9eb

**Comment by jasmine-schoch** [comment]
Added materials function: 18c3573670d6ef47080834e280b67d06637ea2b6
